# Seurat
library(Seurat)
library(dplyr)
library(cowplot)
library(reshape2)
object.data <-read.table(file="./PC_Matrix_All.tsv",check.names=F)
object_name <- CreateSeuratObject(counts = object.data, min.cells = 1, min.features = 1)
object_name <- NormalizeData(object = object_name, normalization.method = "LogNormalize",scale.factor = 10000)
object_name <- FindVariableFeatures(object = object_name, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(x = object_name)
object_name <- ScaleData(object = object_name, features = all.genes)
object_name <- RunPCA(object = object_name, features = VariableFeatures(object = object_name),npcs = 100)
object_name <- FindNeighbors(object = object_name, dims = 1:100)
object_name <- FindClusters(object = object_name, resolution = 0.5)
object_name <- RunUMAP(object = object_name, dims = 1:100)
pdf("PC_Matrix_All.pdf")
DimPlot(object = object_name, reduction = "umap",label=TRUE)
dev.off()
saveRDS(object_name, file = "PC_Matrix_All_0.5.rds")

# Get_coordinate
library(Seurat)
library(dplyr)
memory .size(size=30000)
data <- readRDS("PC_Matrix_All_0.5.rds")
cluster_ID=as.data.frame(Idents(object = data))
cluster_cor= as.data.frame(Embeddings(object = data,reduction = "umap"))
res=cbind(cluster_ID,cluster_cor)
write.table(res,"PC_Matrix_All_0.5_coor.txt",sep="\t",quote = FALSE)
nordata <- as.data.frame(as.matrix(GetAssayData(object= data)))
write.table(nordata,"PC_Matrix_All_0.5_normalized.txt",sep="\t",quote = FALSE)

# Markers
library(Seurat)
library(dplyr)
library(ggplot2)
library(reshape2)

combined <- readRDS("PC_Matrix_All_0.5.rds")
combined.markers <- FindAllMarkers(object = combined , only.pos = TRUE, min.pct = 0.25, thresh.use = 0.25, test.use = "wilcox")
save(combined.markers, combined, file = "PC_Matrix_All_0.5.marker2ks.Rdata")
topn <- combined.markers  %>% group_by(cluster) %>% top_n(n = 2000, wt = avg_log2FC)
topn <- select(topn, gene, everything())
topn$gene=gsub("-","_",topn$gene)
combined <- ScaleData(object = combined)
write.table(topn,file="PC_Matrix_All_0.5.GeneDiffExp2k.xls",sep="\t",col.names = TRUE,row.names = F,quote=F)
write.table(topn[topn$p_val_adj <= 0.05,],file="]PC_Matrix_All_0.5.GeneDiffExpFilter2k.xls",sep="\t",col.names = TRUE,row.names = F,quote=F)
